#!/bin/bash
set -eu # exit script on errors

echo "copy one-list env"
rsync /home/git/www/onelist/.env .

echo "> npm install"
npm install

# # If build wasn't done on github uncomment this
# echo "> npm run build..."
# npm run build

export MAIN="server"
