#!/bin/bash
set -eu # exit script on errors

nvm use 22.13.1

echo "copy one-list env"
rsync /home/git/www/onelist/.env .

echo "> npm install in server"
cd server && npm install && cd ..

# # If build wasn't done on github uncomment this
# echo "> npm run build..."
# npm run build

export MAIN="server"
