export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REORDER_CATEGORY = 'REORDER_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
