export const ADD_COLLABORATOR = 'ADD_COLLABORATOR';
export const TOGGLE_COLLABORATOR = 'TOGGLE_COLLABORATOR';
export const REMOVE_COLLABORATOR = 'REMOVE_COLLABORATOR';
export const REMOVE_COLLABORATORS = 'REMOVE_COLLABORATORS';
