export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const TOGGLE_PRODUCT_CHECKED = 'TOGGLE_PRODUCT_CHECKED';
export const TOGGLE_PRODUCT_INACTIVE = 'TOGGLE_PRODUCT_INACTIVE';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const INACTIVATE_PRODUCTS = 'INACTIVATE_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
