name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and cache dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Install SSH key
        if: ${{ github.event_name == 'push' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to Server
        if: ${{ github.event_name == 'push' }}
        run: |
          git remote add server git@zolly.ml:repos/onelist.git
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git add build -f
          git commit -m "Build files"
          git push -u server master -f
