name: Bundle Analyzer
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Size Change
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Build client
        working-directory: client
        run: npm run build

      - uses: preactjs/compressed-size-action@v2
        working-directory: client
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: './client/build/**/*.{js,css}'
          strip-hash: "\\b\\w{8}\\."
